# -*- coding: utf-8 -*-
"""decision_trees

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXy4LhPxUwIeirP84GymbpMUkbP0oNQ-
"""

from collections import Counter
data = [
    [12.0, 1.5, 1, 'Wine'],
    [5.0, 2.0, 0, 'Beer'],
    [40.0, 0.0, 1, 'Whiskey'],
    [13.5, 1.2, 1, 'Wine'],
    [4.5, 1.8, 0, 'Beer'],
    [38.0, 0.1, 1, 'Whiskey'],
    [11.5, 1.7, 1, 'Wine'],
    [5.5, 2.3, 0, 'Beer']
]

label_map = {'Wine': 0, 'Beer': 1, 'Whiskey': 2}

X = [row[:3] for row in data]
y = [label_map[row[3]] for row in data]
print(X)
print(y)

def gini(y):
    count = Counter(y)
    total = len(y)

    impurity = 1
    for c in count.values():
        p = c / total
        impurity -= p ** 2

    return impurity

print(gini(y))
print(gini([0, 0, 0]))
print(gini([0, 1]))

def split(X, y, feature, threshold):
    X_left, y_left = [], []
    X_right, y_right = [], []

    for i in range(len(X)):
        if X[i][feature] <= threshold:
            X_left.append(X[i])
            y_left.append(y[i])
        else:
            X_right.append(X[i])
            y_right.append(y[i])

    return X_left, y_left, X_right, y_right

X_l, y_l, X_r, y_r = split(X, y, 0, 10)

print("Left:", X_l, y_l)
print("Right:", X_r, y_r)

def best_split(X, y):
    best_gini = float("inf")
    best_feature = None
    best_threshold = None

    n = len(y)

    for feature in range(len(X[0])):
        values = sorted(set(x[feature] for x in X))

        for threshold in values:
            X_left, y_left, X_right, y_right = split(X, y, feature, threshold)

            if len(y_left) == 0 or len(y_right) == 0:
                continue

            g_left = gini(y_left)
            g_right = gini(y_right)

            weighted_gini = (len(y_left) / n) * g_left + (len(y_right) / n) * g_right

            if weighted_gini < best_gini:
                best_gini = weighted_gini
                best_feature = feature
                best_threshold = threshold

    return best_feature, best_threshold

feature, threshold = best_split(X, y)
print("Best feature:", feature)
print("Best threshold:", threshold)

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

def build_tree(X, y):
    if len(set(y)) == 1:
        return Node(value=y[0])

    feature, threshold = best_split(X, y)

    if feature is None:
        majority_class = max(set(y), key=y.count)
        return Node(value=majority_class)

    X_left, y_left, X_right, y_right = split(X, y, feature, threshold)

    if len(y_left) == 0 or len(y_right) == 0:
        majority_class = max(set(y), key=y.count)
        return Node(value=majority_class)

    left_subtree = build_tree(X_left, y_left)
    right_subtree = build_tree(X_right, y_right)

    return Node(feature=feature, threshold=threshold, left=left_subtree, right=right_subtree)

tree = build_tree(X, y)
print("Tree built successfully")

def predict_one(x, node):
    if node.value is not None:
        return node.value

    if x[node.feature] <= node.threshold:
        return predict_one(x, node.left)
    else:
        return predict_one(x, node.right)

print(predict_one([6.0, 2.1, 0], tree))

test_data = [
    [6.0, 2.1, 0],
    [39.0, 0.05, 1],
    [13.0, 1.3, 1]
]

reverse_map = {0: 'Wine', 1: 'Beer', 2: 'Whiskey'}

for x in test_data:
    pred = predict_one(x, tree)
    print(x, "->", reverse_map[pred])

