# -*- coding: utf-8 -*-
"""knn_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lS9Qp-ZCdhl57soWn0DLyLnmL_5xGobL
"""

import numpy as np

data = [
    [150, 7.0, 1, 'Apple'],
    [120, 6.5, 0, 'Banana'],
    [180, 7.5, 2, 'Orange'],
    [155, 7.2, 1, 'Apple'],
    [110, 6.0, 0, 'Banana'],
    [190, 7.8, 2, 'Orange'],
    [145, 7.1, 1, 'Apple'],
    [115, 6.3, 0, 'Banana']
]

label_map = {
    'Apple': 0,
    'Banana': 1,
    'Orange': 2
}

reverse_map = {
    0: 'Apple',
    1: 'Banana',
    2: 'Orange'
}

X = np.array([row[:3] for row in data], dtype=float)
y = np.array([label_map[row[3]] for row in data])

print(X)
print(y)

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

print(euclidean_distance(X[0], X[1]))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict_one(self, x):
        distances = []

        for i in range(len(self.X_train)):
            dist = euclidean_distance(x, self.X_train[i])
            distances.append((dist, self.y_train[i]))

        distances.sort(key=lambda item: item[0])

        k_nearest_labels = [label for _, label in distances[:self.k]]

        values, counts = np.unique(k_nearest_labels, return_counts=True)
        return values[np.argmax(counts)]

    def predict(self, X_test):
        predictions = []
        for x in X_test:
            predictions.append(self.predict_one(x))
        return np.array(predictions)

# Create model
knn = KNN(k=3)

# Train
knn.fit(X, y)

# Test data
test_data = np.array([
    [118, 6.2, 0],
    [160, 7.3, 1],
    [185, 7.7, 2]
])

# Predict
predictions = knn.predict(test_data)

# Print results
for i, pred in enumerate(predictions):
    print(test_data[i], "->", reverse_map[pred])